apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: kubeflowdeluser
  namespace: kubeflow
spec:
  schedule: "0 0 * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: kubeflowdeluser
            image: harry101031/kubeflowdeluser:v1.0
            env:
            - name: ldaphost 
              value: "10.1.xx.xx"
            - name: basedn 
              value: harry
            - name: basednpw 
              value: password
            - name: bindDN 
              value: "ou=example,dc=example,dc=com"
            args:
            - /bin/sh
            - -c
            - run.sh
          serviceAccountName: kubeflowdeluser-service-account
          restartPolicy: Never
