apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubeflowdeluser-service-account
  namespace: kubeflow
---
# clusterrolebinding
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: kubeflowdeluser-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: kubeflowdeluser-service-account
  namespace: kubeflow